### ISSUE TITLE
Inherited props not expressed in view props

### ISSUE THREAD

**Issue by cem2ran** [cca-io/cca-bs-react-native#6]
I just wanted to bring this to your attention as it's something that is incomplete/missing in bs-react-native as well. This is mostly prevalent in the FlatList component which inherits [props](https://facebook.github.io/react-native/docs/flatlist#props) from `VirtualizedList`, which inherits from `ScrollView`, which inherits from `View`, but `FlatList` bindings don't actually reflect all the props possible from the inheritance hierarchy.

bs-react-native has partially solved this for components that inherit from `View` with [ViewProps.extend](https://github.com/reasonml-community/bs-react-native/blob/6bed135f83ba2a08200da31d19632147bec4e6f1/src/components/ViewProps.re#L26)

**Comment by cknitt** [comment]
Thanks, I will look into this.

(Unfortunately we cannot use something like `ViewProps.extend` without incurring code size / runtime costs, so we'll just need to copy the props everywhere.)

**Comment by cknitt** [comment]
Should be fixed with the latest commits. There are only a few TODOs for special cases left. Further refinement can happen later.
